### ISSUE TITLE
01-binning edits

### ISSUE THREAD

**Issue by 3mmaRand** [Cloud-SPAN/metagenomics03-taxonomic-anno#11]
add time estimate for
`( bwa mem -t 8 ../pilon/pilon.fasta ../../data/illumina_fastq/ERR2935805.fastq | samtools view - -Sb | samtools sort - -@4 -o pilon_short_read_alignment.bam ) &> binning.out &`
took ~ 60 mins

Add examining binning.out
start of file
```
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 396040 sequences (80000080 bp)...
[M::process] read 396040 sequences (80000080 bp)...
[M::mem_process_seqs] Processed 396040 reads in 97.374 CPU sec, 14.114 real sec
[M::mem_process_seqs] Processed 396040 reads in 94.057 CPU sec, 14.927 real sec
[M::process] read 396040 sequences (80000080 bp)...
[M::mem_process_seqs] Processed 396040 reads in 96.829 CPU sec, 15.646 real sec
[M::process] read 396040 sequences (80000080 bp)...
[M::mem_process_seqs] Processed 396040 reads in 92.853 CPU sec, 14.992 real sec
[M::process] read 396040 sequences (80000080 bp)...
[M::mem_process_seqs] Processed 396040 reads in 94.947 CPU sec, 15.328 real sec
[M::process] read 396040 sequences (80000080 bp)...
```

end of file when finished
```
[main] Version: 0.7.17-r1188
[main] CMD: bwa mem -t 8 ../pilon/pilon.fasta ../../../data/illumina_fastq/ERR2935805.fastq
[main] Real time: 3460.681 sec; CPU: 11813.877 sec
[bam_sort_core] merging from 12 files and 4 in-memory blocks...
```

add a time estimate for `samtools index pilon_short_read_alignment.bam` it took 2-3 mins

add a time estimate for `runMetaBat.sh -m 1500 ../pilon/pilon.fasta 

pilon_short_read_alignment.bam` it took 2-3 mins

Correct: checkm lineage_wf  -x fa **mbinning**/pilon.fasta.metabat-bins1500-YYYMMDD_HHMMSS/ checkm/ --reduced_tree -t 8 --tab_table -f MAGs_checkm.tsv

**Comment by evelyngreeves** [comment]
I think this issue belongs in repo metagenomics04-binning_funa

I've fixed it in that repo so will close this issue! 👍
